version: '3'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    depends_on:
      - mongo
    restart: always
    volumes:
      - my-remote-volume:/api

volumes:
  mongodb-data:
  my-remote-volume: